name: Version Build

on:
  push:
    branches: [ develop ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout veyfi-develop
        git status
        git tag
        git rebase develop --ours
        git remote -v
        git push origin veyfi-develop --force
